import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import '../objectbox.g.dart'; // generated by build_runner, see docs/SETUP.md

/// Singleton wrapper around the generated ObjectBox Store.
/// The store lives at <appDocsDir>/objectbox — purely on-device,
/// no remote sync configured (ObjectBox Sync is a paid add-on and
/// is deliberately NOT used here).
class ObjectBoxStore {
  late final Store store;

  ObjectBoxStore._create(this.store);

  static Future<ObjectBoxStore> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final dbDir = p.join(docsDir.path, 'objectbox');
    final store = await openStore(directory: dbDir);
    return ObjectBoxStore._create(store);
  }

  void close() => store.close();
}
